### PR TITLE
Added more to the performance and conclusion

### PR DESCRIPTION
**Pull request by Rooney30**
Added as much as I could find about the performance. Performance is not really mentioned anywhere else. Also made a single statement in the conclusion. Did not want to add too much as we need to all contribute.

### CODE REVIEW

**Comment by kaya-sz** [comment]
Looks good to me! It'd be nice if we could have a more solid way to say what the performance is, but I honestly have no idea how to go about that so I think this is the second best thing.

**Comment by Rooney30** [comment]
Right. I completely agree, it just seems that MIT does not care about performance that much...but doesn't really run into the issue much because it is mostly used for education purposes

**Comment by kaya-sz** [comment]
Especially since their projects are on a much smaller scale, and it's also made by MIT students maybe...? Performance usually isn't the biggest concern for students, speaking as a student lol. Whereas Appsmith has fulltime staff and are targetting businesses, so the difference between the two projects is pretty big.

**Comment by carbonara-mac** [comment]
Great contributions to performance. If we could add some more words I think we could write a little more in the conclusion but great start!

**Pull request merged**
